-- Seed weapon options to dropdown_options table
-- These represent various weapons for character generation

INSERT INTO dropdown_options (field, option) VALUES
('weapon', 'Arrow'),
('weapon', 'Axe'),
('weapon', 'Battleaxe'),
('weapon', 'Blade'),
('weapon', 'Blowgun'),
('weapon', 'Bō (Staff)'),
('weapon', 'Bolo'),
('weapon', 'Bombs'),
('weapon', 'Boomerang'),
('weapon', 'Bow'),
('weapon', 'Bow and Arrow'),
('weapon', 'Chain'),
('weapon', 'Club'),
('weapon', 'Crossbow'),
('weapon', 'Dagger'),
('weapon', 'Dart'),
('weapon', 'Fist'),
('weapon', 'Flail'),
('weapon', 'Giant Gauntlet'),
('weapon', 'Glaive'),
('weapon', 'Greataxe'),
('weapon', 'Greatclub'),
('weapon', 'Greatsword'),
('weapon', 'Gun'),
('weapon', 'Halberd'),
('weapon', 'Hammer'),
('weapon', 'Handaxe'),
('weapon', 'Harpoon'),
('weapon', 'Javelin'),
('weapon', 'Knife'),
('weapon', 'Kunai'),
('weapon', 'Kusarigama'),
('weapon', 'Lance'),
('weapon', 'Longbow'),
('weapon', 'Longsword'),
('weapon', 'Mace'),
('weapon', 'Maul'),
('weapon', 'Morningstar'),
('weapon', 'Net'),
('weapon', 'Pike'),
('weapon', 'Quarterstaff'),
('weapon', 'Rapier'),
('weapon', 'Revolver'),
('weapon', 'Rifle'),
('weapon', 'Scimitar'),
('weapon', 'Scythe'),
('weapon', 'Shield'),
('weapon', 'Shortbow'),
('weapon', 'Shortsword'),
('weapon', 'Shotgun'),
('weapon', 'Shuriken'),
('weapon', 'Sickle'),
('weapon', 'Sling'),
('weapon', 'Slingshot'),
('weapon', 'Spear'),
('weapon', 'Staff'),
('weapon', 'Stick'),
('weapon', 'Sword'),
('weapon', 'Trident'),
('weapon', 'Wand'),
('weapon', 'War Pick'),
('weapon', 'Warhammer'),
('weapon', 'Whip')
ON CONFLICT (field, option) DO NOTHING;

