-- Seed element options to dropdown_options table
-- These represent various elements for character generation

INSERT INTO dropdown_options (field, option) VALUES
('element', 'Aether'),
('element', 'Air'),
('element', 'Cloud'),
('element', 'Dark'),
('element', 'Death'),
('element', 'Earth'),
('element', 'Electricity'),
('element', 'Energy'),
('element', 'Fire'),
('element', 'Ghost'),
('element', 'Gravity'),
('element', 'Heal'),
('element', 'Ice'),
('element', 'Lava'),
('element', 'Light'),
('element', 'Lightning'),
('element', 'Magic'),
('element', 'Metal'),
('element', 'Moon'),
('element', 'Nature'),
('element', 'Paper'),
('element', 'Salt'),
('element', 'Sand'),
('element', 'Sea'),
('element', 'Shadow'),
('element', 'Sky'),
('element', 'Smoke'),
('element', 'Snow'),
('element', 'Soul'),
('element', 'Sound'),
('element', 'Space'),
('element', 'Star'),
('element', 'Steam'),
('element', 'Time'),
('element', 'Void'),
('element', 'Water'),
('element', 'Weather'),
('element', 'Wind'),
('element', 'Wood')
ON CONFLICT (field, option) DO NOTHING;

