-- Seed setting/location options to dropdown_options table
-- These represent various locations and settings for character generation

INSERT INTO dropdown_options (field, option) VALUES
('setting', 'A Villa', 1),
('setting', 'Abattoir (Slaughterhouse)', 2),
('setting', 'Abbey', 3),
('setting', 'Academy', 4),
('setting', 'Academy (Alchemist)', 5),
('setting', 'Academy (Arcane)', 6),
('setting', 'Academy (Artificer''s)', 7),
('setting', 'Academy (Bards)', 8),
('setting', 'Academy (Healers)', 9),
('setting', 'Academy (Mages)', 10),
('setting', 'Academy (Military)', 11),
('setting', 'Academy (Naval)', 12),
('setting', 'Academy (Royal)', 13),
('setting', 'Academy (Science)', 14),
('setting', 'An Oasis', 15),
('setting', 'Aquarium', 16),
('setting', 'Aqueduct', 17),
('setting', 'Arcade', 18),
('setting', 'Archives', 19),
('setting', 'Archway', 20),
('setting', 'Arena', 21),
('setting', 'Arena (Gladiatorial)', 22),
('setting', 'Arena (Music)', 23),
('setting', 'Arena (Performance)', 24),
('setting', 'Arena (Racing)', 25),
('setting', 'Arena (Sports)', 26),
('setting', 'Army Base', 27),
('setting', 'Art Gallery', 28),
('setting', 'Art Museum', 29),
('setting', 'Asylum', 30),
('setting', 'Auction House', 31),
('setting', 'Auditorium', 32),
('setting', 'Aviary', 33),
('setting', 'Bakery', 34),
('setting', 'Balcony', 35),
('setting', 'Bar', 36),
('setting', 'Barn', 37),
('setting', 'Barracks', 38),
('setting', 'Basement', 39),
('setting', 'Basement (Cellar)', 40),
('setting', 'Bathhouse', 41),
('setting', 'Battle Ground', 42),
('setting', 'Bazaar', 43),
('setting', 'Beach', 44),
('setting', 'Behind a Waterfall', 45),
('setting', 'Bistro', 46),
('setting', 'Black Market', 47),
('setting', 'Black Market (Underground Market)', 48),
('setting', 'Blue Lagoon', 49),
('setting', 'Board (Message)', 50),
('setting', 'Board (Quest)', 51),
('setting', 'Boutique', 52),
('setting', 'Brewery', 53),
('setting', 'Bridge', 54),
('setting', 'Bridge (Covered Bridge)', 55),
('setting', 'Bridge (Draw Bridge)', 56),
('setting', 'Bridge (Rope Bridge)', 57),
('setting', 'Bridge (Sky Bridge)', 58),
('setting', 'Broadway', 59),
('setting', 'Brothel', 60),
('setting', 'Bungalow', 61),
('setting', 'Burial Mound', 62),
('setting', 'Cabin', 63),
('setting', 'Cache', 64),
('setting', 'Cache (Pirates)', 65),
('setting', 'Cache (Rebel)', 66),
('setting', 'Cache (Smugglers)', 67),
('setting', 'Cache (Thieves)', 68),
('setting', 'Caer / Cair (Stronghold)', 69),
('setting', 'Cafe', 70),
('setting', 'Cairn', 71),
('setting', 'Canal', 72),
('setting', 'Caravan (Wagons)', 73),
('setting', 'Caravan (Merchant)', 74),
('setting', 'Caravan (Military)', 75),
('setting', 'Caravan (Nomads)', 76),
('setting', 'Caravan (Pilgrims)', 77),
('setting', 'Caravan (Prison)', 78),
('setting', 'Caravan (Refugee)', 79),
('setting', 'Caravan (Settlers)', 80),
('setting', 'Caravan (Slavers)', 81),
('setting', 'Casino', 82),
('setting', 'Casino (Gambling Hall)', 83),
('setting', 'Castle', 84),
('setting', 'Catacombs', 85),
('setting', 'Cathedral', 86),
('setting', 'Causeway', 87),
('setting', 'Cellar', 88),
('setting', 'Cellar (Root)', 89),
('setting', 'Cellar (Storm)', 90),
('setting', 'Cellar (Wine)', 91),
('setting', 'Cemetery', 92),
('setting', 'Chain Tower', 93),
('setting', 'Chapel', 94),
('setting', 'Chapel Bridge', 95),
('setting', 'Chateau', 96),
('setting', 'Church', 97),
('setting', 'Circle of Stones', 98),
('setting', 'Circle of Wagons', 99),
('setting', 'Circus', 100),
('setting', 'Cistern', 101),
('setting', 'Citadel', 102),
('setting', 'City', 103),
('setting', 'City Hall', 104),
('setting', 'Civic Center', 105),
('setting', 'Cliff Dwellings', 106),
('setting', 'Clinic', 107),
('setting', 'Clock Tower', 108),
('setting', 'College', 109),
('setting', 'College (Alchemist)', 110),
('setting', 'College (Arcane)', 111),
('setting', 'College (Bards)', 112),
('setting', 'College (Healers)', 113),
('setting', 'College (Mages)', 114),
('setting', 'College (Naval)', 115),
('setting', 'College (Of Artificers)', 116),
('setting', 'College (Of Science)', 117),
('setting', 'College (Royal)', 118),
('setting', 'Colosseum', 119),
('setting', 'Community Center', 120),
('setting', 'Conservatory', 121),
('setting', 'Conservatory (Greenhouse)', 122),
('setting', 'Corral', 123),
('setting', 'Corral (Cattle)', 124),
('setting', 'Corral (Horse)', 125),
('setting', 'Corral (Livestock)', 126),
('setting', 'Cottage', 127),
('setting', 'Courthouse', 128),
('setting', 'Crater Lake', 129),
('setting', 'Crematorium', 130),
('setting', 'Croft', 131),
('setting', 'Crypt', 132),
('setting', 'Dam', 133),
('setting', 'Dance Studio', 134),
('setting', 'Death Valley', 135),
('setting', 'Den', 136),
('setting', 'Den (Assassins)', 137),
('setting', 'Den (Drug)', 138),
('setting', 'Den (Gambling)', 139),
('setting', 'Den (Hookah)', 140),
('setting', 'Den (Opium)', 141),
('setting', 'Den (Smugglers)', 142),
('setting', 'Den (Thieves)', 143),
('setting', 'Desert', 144),
('setting', 'Dig Site', 145),
('setting', 'Dig Site (Fossils)', 146),
('setting', 'Dig Site (Minerals)', 147),
('setting', 'Dig Site (Ruins)', 148),
('setting', 'Dike', 149),
('setting', 'Dock', 150),
('setting', 'Dock (Boat)', 151),
('setting', 'Dock (Ship)', 152),
('setting', 'Dock (Airship)', 153),
('setting', 'Dockyard', 154),
('setting', 'Dojo', 155),
('setting', 'Dojo (Sparring Hall)', 156),
('setting', 'Dojo (Training Hall)', 157),
('setting', 'Dome', 158),
('setting', 'Drug Den', 159),
('setting', 'Drug Lounge', 160),
('setting', 'Drug Parlor', 161),
('setting', 'Dugout', 162),
('setting', 'Dugout (Pit-House)', 163),
('setting', 'Dungeon', 164),
('setting', 'Embassy', 165),
('setting', 'Embassy (Country)', 166),
('setting', 'Embassy (Race)', 167),
('setting', 'Embassy (Realm)', 168),
('setting', 'Embassy (World)', 169),
('setting', 'Emporium', 170),
('setting', 'Estate', 171),
('setting', 'Factory', 172),
('setting', 'Factory (Assembly Line)', 173),
('setting', 'Fairgrounds', 174),
('setting', 'Farm', 175),
('setting', 'Farm (Animal)', 176),
('setting', 'Farm (Crop)', 177),
('setting', 'Farm (Dairy)', 178),
('setting', 'Farm (Share Croppers)', 179),
('setting', 'Farmer''s Market', 180),
('setting', 'Farmhouse', 181),
('setting', 'Ferry', 182),
('setting', 'Fighting Pit', 183),
('setting', 'Fisherman''s Wharf', 184),
('setting', 'Florist', 185),
('setting', 'Flotilla', 186),
('setting', 'Flotilla (Town)', 187),
('setting', 'Flotilla (Village)', 188),
('setting', 'Flotilla (City)', 189),
('setting', 'Forest', 190),
('setting', 'Forester''s House', 191),
('setting', 'Forge', 192),
('setting', 'Fort', 193),
('setting', 'Fortress', 194),
('setting', 'Fort (Coastal)', 195),
('setting', 'Fort (Island)', 196),
('setting', 'Fort (Mountain)', 197),
('setting', 'Fort (Sea)', 198),
('setting', 'Fort (Wooden)', 199),
('setting', 'Fort (Stone)', 200),
('setting', 'Fort (Metal)', 201),
('setting', 'Fortifications', 202),
('setting', 'Fortifications (Cheval De Frise)', 203),
('setting', 'Fortifications (Moat)', 204),
('setting', 'Fortifications (Palisade)', 205),
('setting', 'Fortifications (Towers)', 206),
('setting', 'Fortifications (Trench)', 207),
('setting', 'Fortifications (Wall)', 208),
('setting', 'Fortifications (Wooden Stakes)', 209),
('setting', 'Funeral Home', 210),
('setting', 'Gallery', 211),
('setting', 'Gallows', 212),
('setting', 'Gallows (Gibbet)', 213),
('setting', 'Gambling Den', 214),
('setting', 'Gambling Hall', 215),
('setting', 'Gambling Lounge', 216),
('setting', 'Gambling Parlor', 217),
('setting', 'Garden', 218),
('setting', 'Gardens', 219),
('setting', 'Garden (Crop)', 220),
('setting', 'Garden (Flower)', 221),
('setting', 'Garden (Hanging)', 222),
('setting', 'Garden (Herb)', 223),
('setting', 'Garden (Mushroom)', 224),
('setting', 'Garden (Rock)', 225),
('setting', 'Garden (Rooftop)', 226),
('setting', 'Garden (Sculpture)', 227),
('setting', 'Garden (Zen)', 228),
('setting', 'Garrison', 229),
('setting', 'Gate House', 230),
('setting', 'Gate', 231),
('setting', 'Gates', 232),
('setting', 'Ghost Town', 233),
('setting', 'Giant''s Causeway', 234),
('setting', 'Gibbet', 235),
('setting', 'Glacier', 236),
('setting', 'Granary', 237),
('setting', 'Grange', 238),
('setting', 'Grave', 239),
('setting', 'Grave (Fresh)', 240),
('setting', 'Grave (Marker)', 241),
('setting', 'Grave (Mass)', 242),
('setting', 'Grave (Open)', 243),
('setting', 'Grave (Site)', 244),
('setting', 'Grave (Stone)', 245),
('setting', 'Grave (Vacated)', 246),
('setting', 'Grave (Yard)', 247),
('setting', 'Graveyard', 248),
('setting', 'Greenhouse', 249),
('setting', 'Grounds', 250),
('setting', 'Grounds (Burial)', 251),
('setting', 'Grounds (Fair)', 252),
('setting', 'Grounds (Parade)', 253),
('setting', 'Grounds (Sacred)', 254),
('setting', 'Grounds (Tourney)', 255),
('setting', 'Grounds (Training)', 256),
('setting', 'Guard Post', 257),
('setting', 'Guild', 258),
('setting', 'Guild Hall', 259),
('setting', 'Guild House', 260),
('setting', 'Haberdashery', 261),
('setting', 'Hall', 262),
('setting', 'Hall (City)', 263),
('setting', 'Hall (Gambling)', 264),
('setting', 'Hall (Guild)', 265),
('setting', 'Hall (Mead)', 266),
('setting', 'Hall (Meeting)', 267),
('setting', 'Hall (Music)', 268),
('setting', 'Hall (Opera)', 269),
('setting', 'Hall (Town)', 270),
('setting', 'Hall (Training)', 271),
('setting', 'Harbor', 272),
('setting', 'Hatchery', 273),
('setting', 'Hatchery (Animal)', 274),
('setting', 'Hatchery (Beast)', 275),
('setting', 'Hatchery (Monster)', 276),
('setting', 'Heaven', 277),
('setting', 'Hedge Maze', 278),
('setting', 'Henge', 279),
('setting', 'Hideout', 280),
('setting', 'Hold', 281),
('setting', 'Horreum', 282),
('setting', 'Horreum (Warehouse)', 283),
('setting', 'Hospital', 284),
('setting', 'Hostel', 285),
('setting', 'Hostel (Bed & Breakfast)', 286),
('setting', 'House', 287),
('setting', 'House (Bath)', 288),
('setting', 'House (Boat)', 289),
('setting', 'House (Coach)', 290),
('setting', 'House (Coffee)', 291),
('setting', 'House (Farm)', 292),
('setting', 'House (Guest)', 293),
('setting', 'House (Guild)', 294),
('setting', 'House (Long)', 295),
('setting', 'House (Manor)', 296),
('setting', 'House (Opera)', 297),
('setting', 'House (Ritual)', 298),
('setting', 'House (Safe)', 299),
('setting', 'House (Smoke)', 300),
('setting', 'House (Summer)', 301),
('setting', 'House (Tea)', 302),
('setting', 'House (Theater)', 303),
('setting', 'House (Turf)', 304),
('setting', 'House (Winter)', 305),
('setting', 'Hovel', 306),
('setting', 'Hut', 307),
('setting', 'Huts', 308),
('setting', 'Hut (Adobe)', 309),
('setting', 'Hut (Cloth)', 310),
('setting', 'Hut (Earthen)', 311),
('setting', 'Hut (Grass)', 312),
('setting', 'Hut (Hide)', 313),
('setting', 'Hut (Ice)', 314),
('setting', 'Hut (Mud)', 315),
('setting', 'Hut (Snow)', 316),
('setting', 'Hut (Stone)', 317),
('setting', 'Hut (Straw)', 318),
('setting', 'Hut (Wood)', 319),
('setting', 'Inn', 320),
('setting', 'Island', 321),
('setting', 'Jail', 322),
('setting', 'Junkyard', 323),
('setting', 'Keep', 324),
('setting', 'Kremlin', 325),
('setting', 'Labyrinth', 326),
('setting', 'Library', 327),
('setting', 'Library (Arcane)', 328),
('setting', 'Library (Great)', 329),
('setting', 'Library (Royal)', 330),
('setting', 'Lift', 331),
('setting', 'Lift (Wench & Platform)', 332),
('setting', 'Lighthouse', 333),
('setting', 'Lock', 334),
('setting', 'Locks', 335),
('setting', 'Lock (Waterway)', 336),
('setting', 'Lodge', 337),
('setting', 'Lodge (Hunting)', 338),
('setting', 'Lodge (Masons)', 339),
('setting', 'Lodge (Medicine)', 340),
('setting', 'Lodge (Porters)', 341),
('setting', 'Lodge (Safari)', 342),
('setting', 'Lodge (Secret Society)', 343),
('setting', 'Lodge (Sweat)', 344),
('setting', 'Lodge (Wardens)', 345),
('setting', 'Lost City', 346),
('setting', 'Lumberyard', 347),
('setting', 'Magical Construct', 348),
('setting', 'Magical Construct (Energy Construct)', 349),
('setting', 'Magical Construct (Giant Levitating Crystal)', 350),
('setting', 'Magical Construct (Moving Sculpture)', 351),
('setting', 'Magical Construct (Rune Stones)', 352),
('setting', 'Magical Construct (Sigil Stones)', 353),
('setting', 'Mall', 354),
('setting', 'Manor', 355),
('setting', 'Marina', 356),
('setting', 'Marker Stone', 357),
('setting', 'Marker Stone (Border Stone)', 358),
('setting', 'Marker Stone (Boundary Stone)', 359),
('setting', 'Market', 360),
('setting', 'Market Place', 361),
('setting', 'Market Square', 362),
('setting', 'Matterhorn', 363),
('setting', 'Mausoleum', 364),
('setting', 'Mead Hall', 365),
('setting', 'Meadow', 366),
('setting', 'Mecca', 367),
('setting', 'Meeting House', 368),
('setting', 'Memorial', 369),
('setting', 'Meteor Crater', 370),
('setting', 'Mews', 371),
('setting', 'Midden', 372),
('setting', 'Midden (Heap)', 373),
('setting', 'Midden (Mound)', 374),
('setting', 'Midden (Pile)', 375),
('setting', 'Mill', 376),
('setting', 'Minaret', 377),
('setting', 'Mine', 378),
('setting', 'Mines', 379),
('setting', 'Mine (Coal)', 380),
('setting', 'Mine (Crystal)', 381),
('setting', 'Mine (Crystal - Normal)', 382),
('setting', 'Mine (Crystal - Magic)', 383),
('setting', 'Mine (Gem Stone)', 384),
('setting', 'Mine (Gem Stone - Normal)', 385),
('setting', 'Mine (Gem Stone - Magic)', 386),
('setting', 'Mine (Guano)', 387),
('setting', 'Mine (Metal)', 388),
('setting', 'Mine (Metal - Normal)', 389),
('setting', 'Mine (Metal - Magic)', 390),
('setting', 'Mine (Mineral)', 391),
('setting', 'Mine (Mineral - Normal)', 392),
('setting', 'Mine (Mineral - Magic)', 393),
('setting', 'Mine (Salt)', 394),
('setting', 'Mine (Substance)', 395),
('setting', 'Moat', 396),
('setting', 'Moat (Dry)', 397),
('setting', 'Moat (Lava)', 398),
('setting', 'Moat (Mud)', 399),
('setting', 'Moat (Quicksand)', 400),
('setting', 'Moat (Spiked)', 401),
('setting', 'Moat (Tar)', 402),
('setting', 'Moat (Water)', 403),
('setting', 'Monastery', 404),
('setting', 'Monolith', 405),
('setting', 'Monument', 406),
('setting', 'Mosque', 407),
('setting', 'Mound', 408),
('setting', 'Mound (Burial)', 409),
('setting', 'Mound (Ceremonial)', 410),
('setting', 'Mound (Midden)', 411),
('setting', 'Mound (Shell)', 412),
('setting', 'Mound (Temple)', 413),
('setting', 'Museum', 414),
('setting', 'No Man''s Land', 415),
('setting', 'Nunnery', 416),
('setting', 'Nunnery (Convent)', 417),
('setting', 'Nursery', 418),
('setting', 'Oasis', 419),
('setting', 'Obelisk', 420),
('setting', 'Observation Tower', 421),
('setting', 'Observatory', 422),
('setting', 'Ocean Floor', 423),
('setting', 'Opera Hall', 424),
('setting', 'Opera House', 425),
('setting', 'Opium Den', 426),
('setting', 'Orchard', 427),
('setting', 'Orphanage', 428),
('setting', 'Outpost', 429),
('setting', 'Paddock', 430),
('setting', 'Palace', 431),
('setting', 'Parade Grounds', 432),
('setting', 'Parade Grounds (Training Grounds)', 433),
('setting', 'Park', 434),
('setting', 'Parlor', 435),
('setting', 'Parlour', 436),
('setting', 'Parlor (Drug)', 437),
('setting', 'Parlor (Massage)', 438),
('setting', 'Parlor (Tattoo)', 439),
('setting', 'Pawnshop', 440),
('setting', 'Pharmacy', 441),
('setting', 'Pier', 442),
('setting', 'Pillar', 443),
('setting', 'Pillars', 444),
('setting', 'Pirate Ship', 445),
('setting', 'Pit', 446),
('setting', 'Pit (Dwelling)', 447),
('setting', 'Pit (Fighting)', 448),
('setting', 'Pit (Monster)', 449),
('setting', 'Pit (Prison)', 450),
('setting', 'Pit (Slave)', 451),
('setting', 'Plantation', 452),
('setting', 'Playground', 453),
('setting', 'Piazza', 454),
('setting', 'Port', 455),
('setting', 'Prison', 456),
('setting', 'Pub', 457),
('setting', 'Public Garden', 458),
('setting', 'Public Square', 459),
('setting', 'Pyramid', 460),
('setting', 'Pyre', 461),
('setting', 'Pyre (Funeral)', 462),
('setting', 'Quarry', 463),
('setting', 'Quarry (Crystal)', 464),
('setting', 'Quarry (Magic Crystal)', 465),
('setting', 'Quarry (Metal)', 466),
('setting', 'Quarry (Mineral)', 467),
('setting', 'Quarry (Stone)', 468),
('setting', 'Quarry (Substance)', 469),
('setting', 'Rainforest', 470),
('setting', 'Ranch', 471),
('setting', 'Ranch (Animal)', 472),
('setting', 'Ranch (Monster)', 473),
('setting', 'Root Cellar', 474),
('setting', 'Ruins', 475),
('setting', 'Rune Stone', 476),
('setting', 'Saloon', 477),
('setting', 'Sanctuary', 478),
('setting', 'Sauna', 479),
('setting', 'Sawmill', 480),
('setting', 'School', 481),
('setting', 'Sculpture', 482),
('setting', 'Sculpture (Large)', 483),
('setting', 'Sculpture (Giant)', 484),
('setting', 'Sculpture (Garden)', 485),
('setting', 'Sculpture (Scale City Model)', 486),
('setting', 'Sea Gate', 487),
('setting', 'Sea Wall', 488),
('setting', 'Sewer', 489),
('setting', 'Sewers', 490),
('setting', 'Shack', 491),
('setting', 'Shanty Town', 492),
('setting', 'Shelter', 493),
('setting', 'Ship Graveyard', 494),
('setting', 'Shipwreck', 495),
('setting', 'Shipyard', 496),
('setting', 'Shipyards', 497),
('setting', 'Shrine', 498),
('setting', 'Shrine (Deity)', 499),
('setting', 'Shrine (Druidic)', 500),
('setting', 'Shrine (Element)', 501),
('setting', 'Shrine (Power)', 502),
('setting', 'Shrine (Environment)', 503),
('setting', 'Shrine (Guardian)', 504),
('setting', 'Shrine (Luck)', 505),
('setting', 'Shrine (Magic)', 506),
('setting', 'Shrine (Old One)', 507),
('setting', 'Shrine (Outsider)', 508),
('setting', 'Shrine (Spirit)', 509),
('setting', 'Siege Tower', 510),
('setting', 'Site', 511),
('setting', 'Site (Building)', 512),
('setting', 'Site (Camp)', 513),
('setting', 'Site (Construction)', 514),
('setting', 'Site (Dig)', 515),
('setting', 'Site (Excavation)', 516),
('setting', 'Site (Grave)', 517),
('setting', 'Site (Ritual)', 518),
('setting', 'Skyscraper', 519),
('setting', 'Slaughter House', 520),
('setting', 'Slums', 521),
('setting', 'Smithy', 522),
('setting', 'Sparring Hall', 523),
('setting', 'Square', 524),
('setting', 'Square (Market)', 525),
('setting', 'Square (Public)', 526),
('setting', 'Square (Town)', 527),
('setting', 'Stables', 528),
('setting', 'Stadium', 529),
('setting', 'Statue', 530),
('setting', 'Statue (Idol)', 531),
('setting', 'Statue (Large)', 532),
('setting', 'Statue (Giant)', 533),
('setting', 'Statue (Guardian)', 534),
('setting', 'Statue (Monument)', 535),
('setting', 'Stockade', 536),
('setting', 'Stockyard', 537),
('setting', 'Stonehenge', 538),
('setting', 'Storehouse', 539),
('setting', 'Warehouse', 540),
('setting', 'Street Vendors', 541),
('setting', 'Street Vendors (Alcove)', 542),
('setting', 'Street Vendors (Booth)', 543),
('setting', 'Street Vendors (Cart)', 544),
('setting', 'Street Vendors (Stall)', 545),
('setting', 'Street Vendors (Stand)', 546),
('setting', 'Street Vendors (Tent)', 547),
('setting', 'Stronghold', 548),
('setting', 'Sunken City', 549),
('setting', 'Sunken Ruins', 550),
('setting', 'Sunken Ship', 551),
('setting', 'Sunken Temple', 552),
('setting', 'Supply Post', 553),
('setting', 'Swamp', 554),
('setting', 'Sweat Shop', 555),
('setting', 'Tailor', 556),
('setting', 'Taphouse', 557),
('setting', 'Tavern', 558),
('setting', 'Tea House', 559),
('setting', 'Tearoom', 560),
('setting', 'Temple', 561),
('setting', 'Tent City', 562),
('setting', 'Tent City (Merchant)', 563),
('setting', 'Tent City (Military)', 564),
('setting', 'Tent City (Nomads)', 565),
('setting', 'Tent City (Pilgrims)', 566),
('setting', 'Tent City (Refugee)', 567),
('setting', 'Tent City (Settlers)', 568),
('setting', 'Tent City (Squatters)', 569),
('setting', 'Tomb', 570),
('setting', 'Totem Pole', 571),
('setting', 'Tower', 572),
('setting', 'Tower (Bell)', 573),
('setting', 'Tower (Chain)', 574),
('setting', 'Tower (Clock)', 575),
('setting', 'Tower (Guard)', 576),
('setting', 'Tower (Peel)', 577),
('setting', 'Tower (Siege)', 578),
('setting', 'Tower (Signal)', 579),
('setting', 'Tower (Watch)', 580),
('setting', 'Tower (Wizard)', 581),
('setting', 'Tower Bridge', 582),
('setting', 'Town', 583),
('setting', 'Town Hall', 584),
('setting', 'Trade Route', 585),
('setting', 'Trading Post', 586),
('setting', 'Train', 587),
('setting', 'Training Grounds', 588),
('setting', 'Training Hall', 589),
('setting', 'Tree House', 590),
('setting', 'Tree Town', 591),
('setting', 'Tunnel', 592),
('setting', 'University', 593),
('setting', 'University (Alchemist)', 594),
('setting', 'University (Arcane)', 595),
('setting', 'University (Artificer''s)', 596),
('setting', 'University (Bards)', 597),
('setting', 'University (Healers)', 598),
('setting', 'University (Mages)', 599),
('setting', 'University (Naval)', 600),
('setting', 'University (Of Science)', 601),
('setting', 'University (Royal)', 602),
('setting', 'Vault', 603),
('setting', 'Villa', 604),
('setting', 'Villa (Large Country House / Estate)', 605),
('setting', 'Village', 606),
('setting', 'Vineyard', 607),
('setting', 'Watch Tower', 608),
('setting', 'Water Mill', 609),
('setting', 'Waterfall', 610),
('setting', 'Well', 611),
('setting', 'Well (Artesian)', 612),
('setting', 'Well (Covered)', 613),
('setting', 'Well (Dry)', 614),
('setting', 'Well (House)', 615),
('setting', 'Well (Of Magic)', 616),
('setting', 'Well (Water)', 617),
('setting', 'Well House', 618),
('setting', 'Wharf', 619),
('setting', 'Windmill', 620),
('setting', 'Winery', 621),
('setting', 'Work Camp', 622),
('setting', 'Yurt', 623),
('setting', 'Zoo', 624),
('setting', 'Zoo (Mundane)', 625),
('setting', 'Zoo (Rare)', 626),
('setting', 'Zoo (Exotic)', 627),
('setting', 'Zoo (Magical)', 628),
('setting', 'Zoo (Alien Creatures)', 629)
ON CONFLICT (field, option) DO NOTHING;

